export const FETCH_PROFILE_FIRST_NAME = "FETCH_PROFILE_FIRST_NAME";
export const FETCH_PROFILE_LAST_NAME = "FETCH_PROFILE_LAST_NAME";
export const FETCH_PROFILE_MOBILE_NUMBER = "FETCH_PROFILE_MOBILE_NUMBER";
export const FETCH_PROFILE_EMAIL = "FETCH_PROFILE_EMAIL";
export const VIEW_PROFILE = "VIEW_PROFILE";
export const RADIO_PROFILE_DATA = "RADIO_PROFILE_DATA";
export const PROFILE_PIC_DATA = "PROFILE_PIC_DATA";
export const RADIO_PROFILE_DATA_MALE = "RADIO_PROFILE_DATA_MALE";
export const RADIO_PROFILE_DATA_FEMALE = "RADIO_PROFILE_DATA_FEMALE";
export const PROFILE_DATE = "PROFILE_DATE";
export const RESET_DATA = "RESET_DATA";


// Product Listing Component
export const PRODUCT_LISTING = "PRODUCT_LISTING";
export const FETCH_PRODUCT_NAME = "FETCH_PRODUCT_NAME";
export const FETCH_PRODUCT_PRICE = "FETCH_PRODUCT_PRICE";
export const FETCH_PRODUCT_DESCRIPTION = "FETCH_PRODUCT_DESCRIPTION";
export const FETCH_PRODUCT_QUANTITY = "FETCH_PRODUCT_QUANTITY";
export const FETCH_PRODUCT_IMAGE = "FETCH_PRODUCT_IMAGE";
export const FETCH_PRODUCT_VARIATION_FLAG = "FETCH_PRODUCT_VARIATION_FLAG";
export const FETCH_PRODUCT_VARIATION_NAME = "FETCH_PRODUCT_VARIATION_NAME";
export const FETCH_PRODUCT_VARIATION_PRICE = "FETCH_PRODUCT_VARIATION_PRICE";
export const FETCH_PRODUCT_VARIATION_QUANTITY = "FETCH_PRODUCT_VARIATION_QUANTITY";
export const FETCH_PRODUCT_VARIATION_IMAGE = "FETCH_PRODUCT_VARIATION_IMAGE";
export const FETCH_TEST = "FETCH_TEST";
export const PRODUCT_RESET_DATA = "PRODUCT_RESET_DATA";


// Single Product Component
export const SINGLE_PRODUCT = "SINGLE_PRODUCT";